"""Initial migration

Revision ID: f3ee07ed3e08
Revises: 
Create Date: 2026-05-09 15:03:00.497572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ee07ed3e08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('PATIENT', 'CAREGIVER', 'DOCTOR', name='userrole'), nullable=True),
    sa.Column('preferred_channel', sa.Enum('WHATSAPP', 'TELEGRAM', 'IVR', 'SMS', 'PUSH', name='reminderchannel'), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('expo_push_token', sa.String(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('conditions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('dosi_level', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('STABLE', 'AT_RISK', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('last_dose_at', sa.DateTime(), nullable=True),
    sa.Column('learned_morning_time', sa.String(), nullable=True),
    sa.Column('learned_afternoon_time', sa.String(), nullable=True),
    sa.Column('learned_night_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('medications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('name_encrypted', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('instructions_encrypted', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adherence_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('medication_id', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('TAKEN', 'MISSED', 'LATE', 'SKIPPED', name='adherencestatus'), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'TELEGRAM', 'IVR', 'SMS', 'PUSH', name='reminderchannel'), nullable=True),
    sa.Column('escalation_stage', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('medication_id', sa.String(), nullable=True),
    sa.Column('time_slot', sa.Enum('MORNING', 'AFTERNOON', 'NIGHT', name='timeslot'), nullable=True),
    sa.Column('scheduled_time', sa.String(), nullable=True),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_schedules')
    op.drop_table('adherence_logs')
    op.drop_table('medications')
    op.drop_table('patient_profiles')
    op.drop_table('users')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
